name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Compile
        id: compiler
        run: GOOS=linux go build main.go

      - name: Compress executables
        id: compresser
        run: zip -j deploy.zip main

      - name: Deploy
        id: aws-deploy
        run: aws lambda update-function-code --function-name=showHelloPapa --zip-file=fileb://deploy.zip
                  